# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "server" do |server|
		server.vm.box = "centos/7"
		server.vm.hostname = "server-01"
		server.vm.network "private_network", ip: "192.168.10.21", virtualbox__intnet: true
		server.vm.provision "shell", path: "server.sh"
	end
	config.vm.define "client" do |client|
		client.vm.box = "centos/7"
		client.vm.hostname = "client-01"
		client.vm.network "private_network", ip: "192.168.10.20", virtualbox__intnet: true
		client.vm.provision "shell", path: "client.sh"
	end
end