Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "nginx-01"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "shell", inline: "yum install epel-release -y"
  config.vm.provision "shell", inline: "yum install nginx -y"
  config.vm.provision "shell", inline: "systemctl start nginx"
end
